#!/bin/bash
cd src/greatappxyz/configuration-service
title='Configuration Service'
echo -n -e "\033]0;$title\007"
sh gradlew build -x test
java -jar build/libs/configuration-service-0.0.1-SNAPSHOT.jar
